[package]
name = "rust-url-shortener"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
uuid = { version = "1.0", features = ["v4"] }
rand = "0.8"
url = "2.2"
lazy_static = "1.4"
log = "0.4"
env_logger = "0.9"